### ISSUE TITLE
Static site demo link returns 404

### ISSUE THREAD

**Issue by mlissner** [betson/irs-efile-viewer#15]
I dunno what's going on with it, but I just noticed that the static site provides this demo link:

https://s3.amazonaws.com/irs-form-990/201541349349307794_public.xml

If you click it, you'll see that it returns a 404. Hm....

**Comment by mlissner** [comment]
Hm, looks like the AWS data has been removed or deprecated or something. Lame. I guess there's no fix here.

**Comment by betson** [comment]
Oh that's a bummer. I was involved with getting that repository published to begin with. Sad to see even the legacy files removed now that the archive is deprecated. Thank you for reporting this, and I've logged it as Issue #16.

You can easily grab a sample XML file from [Nonprofit Explorer](https://projects.propublica.org/nonprofits/), but I doubt they want me linking to one of their files directly. Also likely not easily done if they're doing some auth to their own S3 bucket.
