### ISSUE TITLE
How to drive XSL parameters?

### ISSUE THREAD

**Issue by ghost** [betson/irs-efile-viewer#20]
Hi @betson, I am learning the ropes here by experimenting. 
I see that Form 990 XSL file has a few parameters $RtnDoc, $RtnHdrData, {$ScriptPath} etc.

I was trying to look into "transform.js" about how are you populating those values but couldn't. Could you help? I want to compile the XML and XSL through a top HTML file, but so far no luck.

**Comment by betson** [comment]
@tushar-uwaterloo -- `form_template.xml` defines the shape of the actual XML file that gets transformed. There's a bunch of variables at the top, and then the main form content below. The content gets copied over by `moveHeaderAndMainForm()`, putting it in the `<SubmissionHeaderAndDocument>` node. Then `setFormProperties()` takes data from the form content and copies it into the top-level variables of the template. This completed doc is then passed into the XSLT transformation. This is code that I wrote that mimics how the XSLT files are intended to be used.

The next step is that the XSLT (code that the IRS wrote) pulls out the nodes from the template and saves them as variables during transformation. So what I save as `<SubmissionDocument>` may then get saved as `$RtnDoc`. This is defined in `mef/Stylesheets/$year/CommonPathRef.xsl`. Example: [2016](https://github.com/betson/irs-efile-viewer/blob/4ba327d00656a099a22caa0438db6544db6063e6/mef/Stylesheets/2016/CommonPathRef.xsl)
